services:
  frontend:
    build: ./apps/frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    depends_on:
      - backend

  backend:
    build: ./apps/backend
    ports:
      - "3000:3000"
    environment:
      - REDIS_PASSWORD=mysecretpassword
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_URL=redis://cache:6379
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lastmile
      - JWT_SECRET=supersecret
    depends_on:
      - db

  cache:
    image: redis:latest
    restart: always
    environment:
      REDIS_PASSWORD: mysecretpassword
    ports:
      - "6379:6379"
  

  db:
    image: postgis/postgis:15-3.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lastmile
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  pgdata: